-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgFC8Ao5elSyUXPxM+
lMDYDlIaoD9/oItP/0kK8qSqEtOgCgYIKoZIzj0DAQehRANCAAT4ooQi9I2BftIL
TqHkDj58qlw+nN1IA/AtAirpjgKmrjbsrSTIsXh62pOmlDuxt90zhx0gjyBmEoIs
bgLklAlh
-----END PRIVATE KEY-----