on:
  workflow_dispatch:

jobs:
  build_ios:
    name: Build iOS app
    type: build
    params:
      platform: ios
      profile: production

  submit_ios:
    name: Submit to TestFlight
    needs: [build_ios]
    type: submit
    params:
      platform: ios
      profile: production
      buildId: ${{ needs.build_ios.outputs.buildId }}
